rujabuka/rujabuka/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tickets.urls')),
    path('admin/', admin.site.urls),
]

rujabuka/tickets/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('ver_almocos', views.ver_almocos, name='ver_almocos'),
    path('comprar_ticket/<int:id_almoco>/', views.comprar_ticket, name='comprar_ticket'),
    path('meus_tickets', views.meus_tickets, name='meus_tickets'),
    path('vender_ticket/<int:id>/', views.vender_ticket, name='vender_ticket'),
    path('login', views.logar, name='login'),
    path('logout', views.deslogar, name='logout'),
    path('registrar_user', views.registrar_user, name='registrar_user'),
    path('registrar_profile', views.registrar_profile, name='registrar_profile'),
    #path('searchAluno', views.searchAluno, name='searchAluno'),
    #path('viewTeste', views.viewTeste, name='viewTeste'),
    #path('ver_cursos', views.ver_cursos, name='ver_cursos'),
    path('detalhe_almoco/<int:id>/', views.detalhe_almoco, name='detalhe_almoco'),
    #path('editar_curso/<int:id>/', views.editar_curso, name='editar_curso'),
]

rujabuka/tickets/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Almoco(models.Model):
    data_almoco = models.DateField("Data do almoço", unique=True)
    num_tickets = models.PositiveSmallIntegerField("Número total de tickets")
    tickets_comprados = models.PositiveSmallIntegerField("Tickets Comprados", default=0)
    tickets_disponiveis = models.PositiveSmallIntegerField("Tickets disponíveis")
    cardapio = models.TextField("Cardápio", max_length=255, blank=True, null=True)

    def __str__(self):
        return "Almoço do dia " + str(self.data_almoco)

    def getTicketsComprados(self):
        return self.tickets_comprados

    def getTicketsDisponiveis(self):
        return self.tickets_disponiveis

    def getNumTickets(self):
        return self.num_tickets

    def setNumTickets(self, action):
        if (action == "compra"): #diminui tickets disponiveis e aumenta comprados
            self.tickets_disponiveis -= 1
            self.tickets_comprados += 1
        elif (action == "venda"): #aumenta tickets disponiveis e diminui comprados
            self.tickets_disponiveis += 1
            self.tickets_comprados -= 1
        self.save()
        return
    
class Ticket(models.Model):
    choices_status = [
        ('1', 'Ativo'),
        ('2', 'Usado'),
        ('3', 'Vendido'),
    ]
    data_compra = models.DateField("Data da compra")
    data_fim = models.DateField("Data da venda/uso", null=True, blank=True)
    status = models.CharField(max_length=1, choices=choices_status, default=1)
    almoco = models.ForeignKey('Almoco', models.PROTECT, 'tickets', null=False, blank=False)
    user = models.ForeignKey('ProfileUser', models.PROTECT, 'tickets_comprados', null=False, blank=False, default=1)

    def __str__(self):
        return "Ticket " + str(self.pk)


class Categoria(models.Model):
    choices_tipo = [
        ('1', 'Administração do Sistema'),
        ('2', 'Usuário do Restaurante'),
    ]
    nome = models.CharField("Nome da Categoria", max_length=50)
    tipo = models.CharField("Tipo de Categoria", max_length=1, choices=choices_tipo)
    valorTicket = models.DecimalField("Valor do ticket", max_digits=5, decimal_places=2)

    def __str__(self):
        return self.nome#self.get_tipo_display() + "/" + self.nome

    def get_categorias_user(self):
        return Categoria.objects.filter(tipo='2')

    def get_categorias_admin(self):
        return self.objects.filter(tipo='1')



class ProfileUser(models.Model):
    nome = models.CharField("Nome Completo", max_length=255)
    cpf = models.CharField("CPF (somente números)", max_length=11)
    saldo = models.DecimalField("Saldo", max_digits=5, decimal_places=2)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="perfil")
    categoria = models.ManyToManyField(Categoria, related_name="users")

    def __str__(self):
        return self.nome

    def getSaldo(self):
        return self.saldo

    def setSaldo(self, novo_saldo):
        self.saldo = novo_saldo
        return self.saldo

    def getValorTicket(self):
        return Categoria.objects.get(users=self, tipo='2').valorTicket

    def comprarTicket(self, almoco):
        data_compra = datetime.datetime.now().date()
        status = 1
        if (not self.saldoSuficiente()):
            return "Saldo Insuficiente!"
        if (not Almoco.getTicketsDisponiveis(almoco) > 0):
            return "Tickets esgotados!"
        if (self.ticketJaComprado(almoco)):
            return "Ticket já comprado para esse almoço!"
        self.atualizaSaldo("compra")
        Almoco.setNumTickets(almoco, "compra")
        novo_ticket = Ticket(data_compra=data_compra, user=self, status=status, almoco=almoco)
        novo_ticket.save()
        return 1

    def venderTicket(self, id):
        data_fim = datetime.datetime.now().date()
        status = 3
        self.atualizaSaldo("venda")
        ticket = Ticket.objects.get(pk=id)
        almoco = ticket.almoco
        Almoco.setNumTickets(almoco, "venda")
        ticket.data_fim = data_fim
        ticket.status = status
        ticket.save()
        return

    def atualizaSaldo(self, action):
        valor_ticket = self.getValorTicket()
        saldo_atual = self.getSaldo()
        saldoCompra = saldo_atual - valor_ticket
        saldoVenda = saldo_atual + valor_ticket
        novo_saldo = saldoCompra if (action == "compra") else saldoVenda
        self.setSaldo(novo_saldo)
        self.save()
        return

    def saldoSuficiente(self):
        saldo_atual = self.getSaldo()
        valor_ticket = self.getValorTicket()
        return True if saldo_atual >= valor_ticket else False

    def ticketJaComprado(self, almoco):
        return Ticket.objects.filter(user=self, almoco=almoco, status='1').exists()

rujabuka/tickets/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Almoco, ProfileUser, Ticket, Categoria
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.messages import error



def index(request):
    if request.user.is_authenticated:
        return redirect('ver_almocos')
    return redirect('login')

@login_required
def ver_almocos(request):
    almocos = Almoco.objects.all()

    return render(request, 'tickets/almocos.html', {'almocos': almocos})

@login_required
def meus_tickets(request):
    tickets = Ticket.objects.filter(user=request.user.perfil.id, status="1")
    return render(request, 'tickets/tickets.html', {'tickets': tickets})

@login_required
def detalhe_almoco(request, id):
    almoco = Almoco.objects.get(pk=id)
    return render(request, 'tickets/detalhe_almoco.html', {'almoco': almoco})


@login_required
def comprar_ticket(request, id_almoco):
    almoco = Almoco.objects.get(pk=id_almoco)
    perfil = ProfileUser.objects.get(user=request.user)
    novo_ticket = ProfileUser.comprarTicket(self=perfil, almoco=almoco)
    if (novo_ticket != 1):
        error(request, novo_ticket)
    #almocos = Almoco.objects.all()
    #return render(request, 'tickets/almocos.html', {'almocos': almocos, 'novo_ticket': novo_ticket})
    return redirect("ver_almocos")

    
@login_required
def vender_ticket(request, id):
    perfil = ProfileUser.objects.get(user=request.user)
    perfil.venderTicket(id)
    return redirect("meus_tickets")


def get_perfil_logado(request):
    return request.user.perfil.id



#def changeSaldo(request, value, action)
#    saldoAtual = ProfileUser.getSaldo()
#    valorTicket = ProfileUser.categoria.getV
#    ProfileUser.setSaldo()


def logar(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("ver_almocos")
        else:
            HttpResponse('Usuário e/ou senha incorretos')

    return render(request, 'tickets/login.html')

def deslogar(request):
    logout(request)
    return redirect("/")

def registrar_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        user = User.objects.create_user(username=username, password=password, email=email)
        user.save()
        login(request, user)
        return redirect('registrar_profile') #tem que ir pra página de configurar perfil
    # ao fazer o login, caso o perfil não esteja criado, deve redirecionar
    return render(request, 'tickets/registrar_user.html')

def registrar_profile(request):
    if request.method == "POST":
        name = request.POST.get('name')
        cpf = request.POST.get('cpf')
        user = request.user
        categoria = request.POST.get('categoria')
        saldo=33
        perfil = ProfileUser.objects.create(nome=name, cpf=cpf, saldo=saldo, user=user)
        perfil.categoria.set(categoria)
        perfil.save()
        return redirect('ver_almocos')
    c = Categoria()
    categorias = Categoria.get_categorias_user(c)
    return render(request, 'tickets/registrar_profile.html', {'categorias': categorias })

rujabuka/tickets/templates/tickets/almocos.html
{% extends 'tickets/index.html' %}

{% block content %}
    {% for message in messages %}
        <p>{{ message }}</p>
    {% endfor %}
    <h3>Próximos almoços:</h3>
    <ul>
        {% for almoco in almocos %}
            <li>{{ almoco.data_almoco }} ({{ almoco.tickets_comprados }}/{{ almoco.num_tickets }} tickets):
                <a href="{% url 'detalhe_almoco' almoco.id %}">Detalhes</a><br>
            <a href="{% url 'comprar_ticket' almoco.id %}" class="btn btn-outline-success btn-sm">Comprar Ticket</a><p>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

rujabuka/tickets/templates/tickets/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <title>RuJabuka</title>
</head>
<body>

    <div class="container-fluid">

        <div class="row">
            <div class="col-6 border text-center" id="divTitle">
                <h1>Título</h1>
            </div>
            <div class="col-6 border text-right" id="divUser">
                {% if user.is_authenticated %}
                   <h4>{{ user.perfil.nome }}</h4>
                    <h6>Saldo: R$ {{ user.perfil.saldo }}</h6>
                {% endif %}
            </div>
        </div>

        <div class="row">
            {% block content_base %}
            {% endblock %}
        </div>

    </div>

</body>

{% block index %}
{% endblock %}

rujabuka/tickets/templates/tickets/detalhe_almoco.html
{% extends 'tickets/index.html' %}

{% block content %}

<div class="row">
    <div class="col-12">
        <b>Data do almoço:</b> {{ almoco.data_almoco }}
    </div>
</div>
<div class="row">
    <div class="col-12">
        <b>Tickets comprados:</b> {{ almoco.tickets_comprados }}/{{ almoco.num_tickets }}
    </div>
</div>
<div class="row">
    <div class="col-12">
        <b>Cardápio:</b> {{ almoco.cardapio|linebreaks }}
    </div>
</div>

<div class="row">
    <div class="col-12">
        <a href="{% url 'ver_almocos' %}" class="btn btn-sm btn-outline-danger">Voltar</a>
    </div>
</div>





{% endblock %}

rujabuka/tickets/templates/tickets/index.html
{% extends 'tickets/base.html' %}

{% block content_base %}

    {% if user.is_authenticated %}
            <div class="col-lg-1 border" id="divMenu">
                <div class="row">
                    <a href="{% url 'ver_almocos' %}" class="btn btn-outline-dark btn-sm w-100">
                        Almoços
                    </a>
                </div>
                <div class="row">
                    <a href="{% url 'meus_tickets' %}" class="btn btn-outline-dark btn-sm w-100">
                        Meus Tickets
                    </a>
                </div>
                <div class="row">
                    <a href="#" class="btn btn-outline-dark btn-sm w-100">Menu 3</a>
                </div>
                <div class="row">
                    <a href="#" class="btn btn-outline-dark btn-sm w-100">Menu 4</a>
                </div>
                <div class="row">
                    <a href="#" class="btn btn-outline-dark btn-sm w-100">Menu 5</a>
                </div>
                <div class="row">
                    <a href="{% url 'logout' %}" class="btn btn-outline-dark btn-sm w-100">Logout</a>
                </div>
            </div>
            <div class="col-lg-11 p-3 border" id="divContent">
                {% block content %}
                {% endblock %}
            </div>


{% endif %}



{% endblock %}

rujabuka/tickets/templates/tickets/login.html
{% extends "tickets/index.html" %}

{% block content_base %}
<div class="container w-25 pt-5">
    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome de usuário" required autofocus>
        <br>
        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>
<br>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <a href="{% url 'registrar_user' %}">Registre-se</a>
    </form>
</div>
{% endblock %}

rujabuka/tickets/templates/tickets/registrar_profile.html
{% extends "tickets/base.html" %}

{% block content_base %}
<div class="container w-25 pt-5">
    <form class="form-signin" role="form" action="#" method="post">
        {% csrf_token %}

        <h3 class="form-signin-heading">Cadastre seu Perfil:</h3>

        <input type="text" id="id_name" name="name" class="form-control" placeholder="Nome Completo" required autofocus>
        <br>
        <input type="text" id="id_cpf" name="cpf" class="form-control" placeholder="CPF (somente números)" required>
        <br>
        <label>Vínculo com a FCAV: </label><br>
        <select name="categoria" id="id_categoria" multiple="multiple">
            {% for categoria in categorias %}
            <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
            {% endfor %}
        </select>
        <p>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Registrar">Registrar</button>

    </form>
</div>
{% endblock %}

rujabuka/tickets/templates/tickets/registrar_user.html
{% extends "tickets/base.html" %}

{% block content_base %}
<div class="container w-25 pt-5">
    <form class="form-signin" role="form" action="{% url 'registrar_user' %}" method="post">
        {% csrf_token %}

        <h3 class="form-signin-heading">Registre-se:</h3>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome de usuário" required autofocus>
        <br>
        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>
        <br>
        <input type="email" id="id_email" name="email" class="form-control" placeholder="E-mail" required>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Registrar">Registrar</button>

    </form>
</div>
{% endblock %}

rujabuka/tickets/templates/tickets/tickets.html
{% extends 'tickets/index.html' %}

{% block content %}


        {% if tickets %}
        <ul>
            <h3>Meus tickets:</h3>
            {% for ticket in tickets %}
                <li>{{ ticket.almoco }}: <a href="#">Detalhes</a><br>
                <a href="{% url 'vender_ticket' ticket.id %}" class="btn btn-outline-danger btn-sm">Vender Ticket</a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            Nenhum ticket ativo!
        {% endif %}



{% endblock %}